#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '9f1a745ce00de760528cb955c42ed3339c2c6288 *'
__dependency_versions__ = {
    'boost': '1.60',
    'gsl': '1.16.lsst3',
    'eigen': '3.2.5.lsst1',
    'base': '2.2016.10-2-ge90c490+1',
    'pex_exceptions': '2016_01.0-1-gfde6942+1',
    'python': 'unknown',
}
__all__ = ('__version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
